name: Build Loyalmed prometheuys exporter
on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.0'

      - name: Init project
        run: make init

      - name: Get version
        run: echo "EXPORTER_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Build
        run: make build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: tg_whi_exporter
          path: bin/

      